DO $$ BEGIN
  CREATE TYPE "CAMPAIGN_EXTENSION_STATUS" AS ENUM ('NONE', 'PENDING', 'APPROVED', 'REJECTED');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "campaigns"
  ADD COLUMN IF NOT EXISTS "extension_status" "CAMPAIGN_EXTENSION_STATUS" NOT NULL DEFAULT 'NONE',
  ADD COLUMN IF NOT EXISTS "requested_deadline" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "extension_requested_at" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "extension_reviewed_at" TIMESTAMP(3);
