import { Controller, Headers, HttpCode, Post, Req, UnauthorizedException } from '@nestjs/common';
import { ApiHeader, ApiOperation, ApiTags } from '@nestjs/swagger';
import { Request } from 'express';
import * as crypto from 'crypto';
import { PaystackService } from './paystack.service';

@ApiTags('Payments')
@Controller('webhooks')
export class PaystackWebhookController {
    constructor(private readonly paystackService: PaystackService) {}

    @Post('paystack')
    @HttpCode(200)
    @ApiOperation({
        summary: 'Paystack webhook listener',
        description:
            'Receives Paystack webhooks, validates the signature, acknowledges immediately, and processes the event asynchronously.',
    })
    @ApiHeader({
        name: 'x-paystack-signature',
        description: 'HMAC SHA512 signature generated by Paystack using your secret key.',
        required: true,
    })
    async handleWebhook(
        @Req() req: Request & { rawBody?: Buffer },
        @Headers('x-paystack-signature') signature?: string,
    ) {
        const secret = process.env.PAYSTACK_SECRET_KEY;
        if (!secret) throw new UnauthorizedException('Paystack secret not configured');

        const raw = req.rawBody;
        if (!raw || !Buffer.isBuffer(raw)) {
            throw new UnauthorizedException('Missing raw body for signature verification');
        }

        const expected = crypto.createHmac('sha512', secret).update(raw).digest('hex');
        if (!signature || signature !== expected) {
            throw new UnauthorizedException('Invalid Paystack signature');
        }

        const event = req.body as Record<string, any>;
        void this.paystackService.processWebhookEvent(event).catch((error) => {
            console.error('Failed to process Paystack webhook', error);
        });

        return { data: { received: true } };
    }
}
